"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_bg1)\
$os\
$username\
$hostname\
[](fg:color_bg2 bg:color_bg3 )\
$directory\
[](fg:color_bg3 bg:color_bg4)\
$git_branch\
$git_status\
[](fg:color_bg4 bg:color_bg5)\
$elixir\
$erlang\
$c\
$rust\
$nodejs\
$python\
[](fg:color_bg5 bg:color_bg6)\
$battery\
$cmd_duration\
[](fg:color_bg6 bg:color_bg7)\
$time\
[ ](fg:color_bg7)\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'

#color_bg1 = '#b16286'
color_bg1 = '#d65d0e'
color_bg2 = '#d65d0e'
color_bg3 = '#d79921'
color_bg4 = '#689d6a'
color_bg5 = '#458588'
color_bg6 = '#665c54'
color_bg7 = '#3c3836'

color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

add_newline = 'false'

[os]
disabled = false
style = "bg:color_bg1 fg:color_fg0"
format = "[$symbol]($style)"

[os.symbols]
Windows = "󰍲 "
Ubuntu = "󰕈 "
SUSE = " "
Raspbian = "󰐿 "
Mint = "󰣭 "
Macos = "󰀵 "
Manjaro = " "
Linux = "󰌽 "
Gentoo = "󰣨 "
Fedora = "󰣛 "
Alpine = " "
Amazon = " "
Android = " "
Arch = "󰣇 "
Artix = "󰣇 "
EndeavourOS = " "
CentOS = " "
Debian = "󰣚 "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "
NixOS = " "

[username]
show_always = false
style_user = "bg:color_bg1 fg:color_fg0"
style_root = "bg:color_bg1 fg:color_fg0"
format = '[$user]($style)'

[hostname]
ssh_only = true
ssh_symbol = ""
style = "bg:color_bg2 fg:color_fg0"
format = '[@$hostname ]($style)'

[directory]
style = "fg:color_fg0 bg:color_bg3"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = ""

[git_branch]
symbol = ""
style = "bg:color_bg4"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_bg4)]($style)'

[git_status]
style = "bg:color_bg4"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_bg4)]($style)'

[elixir]
symbol = ""
style = "bg:color_bg5"
format = '[[ $symbol( $version)](fg:color_fg0 bg:color_bg5)]($style)'
version_format = "${raw}"

[erlang]
symbol = "OTP"
style = "bg:color_bg5"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_bg5)]($style)'
version_format = "${raw}"
detect_files = ['rebar.config', 'elang.mk', 'mix.exs']

[nodejs]
symbol = ""
style = "bg:color_bg5"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_bg5)]($style)'

[c]
symbol = " "
style = "bg:color_bg5"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_bg5)]($style)'

[rust]
symbol = ""
style = "bg:color_bg5"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_bg5)]($style)'

[python]
symbol = ""
style = "bg:color_bg5"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_bg5)]($style)'

[container]
format = '[[ $symbol $name ](fg:color_fg0 bg:color_bg6)]($style)'

[battery]
format = '[[ $symbol ](fg:color_fg0 bg:color_bg6)]($style)'
[[battery.display]]
threshold = 15

[cmd_duration]
min_time = 500
format = '[[  $duration ](fg:color_fg0 bg:color_bg6)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg7"
format = '[[  $time ](fg:color_fg0 bg:color_bg7)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'


# Not used

[docker_context]
disabled = true
symbol = ""
style = "bg:color_bg6"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg6)]($style)'

[conda]
disabled = true
style = "bg:color_bg6"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg6)]($style)'


[golang]
disabled = true
symbol = ""
style = "bg:color_bg5"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_bg5)]($style)'

[php]
disabled = true
symbol = ""
style = "bg:color_bg5"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_bg5)]($style)'

[java]
disabled = true
symbol = ""
style = "bg:color_bg5"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_bg5)]($style)'

[kotlin]
disabled = true
symbol = ""
style = "bg:color_bg5"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_bg5)]($style)'

[haskell]
disabled = true
symbol = ""
style = "bg:color_bg5"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_bg5)]($style)'
